Disable 'InjectedTest' which is generated by the maven-hpi-plugin and is currently throwing an error when executed: java.lang.NoSuchMethodError: hudson.os.PosixAPI.jnr()Ljnr/posix/POSIX; 	at org.jvnet.hudson.test.HudsonTestCase.<clinit>(HudsonTestCase.java:1994) 	at org.jvnet.hudson.test.JellyTestSuiteBuilder$JellyTestSuite.<init>(JellyTestSuiteBuilder.java:129) 	at org.jvnet.hudson.test.JellyTestSuiteBuilder$JellyTestSuite.<init>(JellyTestSuiteBuilder.java:128) 	at org.jvnet.hudson.test.JellyTestSuiteBuilder.build(JellyTestSuiteBuilder.java:56) 	at org.jvnet.hudson.test.PluginAutomaticTestBuilder.build(PluginAutomaticTestBuilder.java:55) 	at InjectedTest.suite(InjectedTest.java:15)